/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.school.media;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Haveri
 */
public class MainFrame extends javax.swing.JFrame {

    ArrayList<Mediateke> MList = new ArrayList<>();
    String url;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        VideoInputPanel = new javax.swing.JPanel();
        VideoInputlabel = new javax.swing.JLabel();
        VideoFileNameValue = new javax.swing.JTextField();
        VideoFileNameText = new javax.swing.JLabel();
        VideoFileTypeValue = new javax.swing.JTextField();
        VideoFileTypeText = new javax.swing.JLabel();
        VideoSizeValue = new javax.swing.JTextField();
        VideoSizeText = new javax.swing.JLabel();
        VideoAuthorValue = new javax.swing.JTextField();
        VideoAuthorText = new javax.swing.JLabel();
        VideoTitleValue = new javax.swing.JTextField();
        VideoTitleText = new javax.swing.JLabel();
        VideoLengthValue = new javax.swing.JTextField();
        VideoLengthText = new javax.swing.JLabel();
        VideoQualityValue = new javax.swing.JTextField();
        VideoQualityText = new javax.swing.JLabel();
        VideoGenreValue = new javax.swing.JTextField();
        VideoGenreText = new javax.swing.JLabel();
        MusicInputPanel = new javax.swing.JPanel();
        MusicInputlabel = new javax.swing.JLabel();
        MusicFileNameValue = new javax.swing.JTextField();
        MusicFileNameText = new javax.swing.JLabel();
        MusicFileTypeValue = new javax.swing.JTextField();
        MusicFileTypeText = new javax.swing.JLabel();
        MusicSizeValue = new javax.swing.JTextField();
        MusicSizeText = new javax.swing.JLabel();
        MusicAuthorValue = new javax.swing.JTextField();
        MusicAuthorText = new javax.swing.JLabel();
        MusicTitleValue = new javax.swing.JTextField();
        MusicTitleText = new javax.swing.JLabel();
        MusicLengthValue = new javax.swing.JTextField();
        MusicLengthText = new javax.swing.JLabel();
        MusicBitrateValue = new javax.swing.JTextField();
        MusicBItrateText = new javax.swing.JLabel();
        MusicFeaturedValue = new javax.swing.JTextField();
        MusicFeaturedText = new javax.swing.JLabel();
        MusicGenreValue = new javax.swing.JTextField();
        MusicGenreText = new javax.swing.JLabel();
        EbookInputPanel = new javax.swing.JPanel();
        EbookInputlabel = new javax.swing.JLabel();
        EbookFileNameValue = new javax.swing.JTextField();
        EbookFileNameText = new javax.swing.JLabel();
        EbookFileTypeValue = new javax.swing.JTextField();
        EbookFileTypeText = new javax.swing.JLabel();
        EbookSizeValue = new javax.swing.JTextField();
        EbookSizeText = new javax.swing.JLabel();
        EbookAuthorValue = new javax.swing.JTextField();
        EbookAuthorText = new javax.swing.JLabel();
        EbookTitleValue = new javax.swing.JTextField();
        EbookTitleText = new javax.swing.JLabel();
        EbookPagesValue = new javax.swing.JTextField();
        EbookPagesText = new javax.swing.JLabel();
        EbookGenreValue = new javax.swing.JTextField();
        EbookGenreText = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        MediaTypeCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ObjectCount = new javax.swing.JLabel();
        responseField = new javax.swing.JLabel();
        useFile = new javax.swing.JButton();
        useDatabase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObjectTable = new javax.swing.JTable();
        usingField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("List of Media");

        VideoInputlabel.setText("Video Input Area");

        VideoFileNameText.setText("File Name");

        VideoFileTypeText.setText("File Type");

        VideoSizeText.setText("Size (Int)");

        VideoAuthorText.setText("Author");

        VideoTitleText.setText("Title");

        VideoLengthText.setText("Length");

        VideoQualityText.setText("Quality (Int)");

        VideoGenreText.setText("Genre");

        javax.swing.GroupLayout VideoInputPanelLayout = new javax.swing.GroupLayout(VideoInputPanel);
        VideoInputPanel.setLayout(VideoInputPanelLayout);
        VideoInputPanelLayout.setHorizontalGroup(
            VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoInputPanelLayout.createSequentialGroup()
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VideoInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VideoInputlabel))
                    .addGroup(VideoInputPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VideoFileNameText)
                            .addComponent(VideoFileTypeText)
                            .addComponent(VideoSizeText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VideoFileNameValue)
                            .addComponent(VideoFileTypeValue)
                            .addComponent(VideoSizeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VideoAuthorText)
                            .addComponent(VideoTitleText)
                            .addComponent(VideoLengthText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VideoLengthValue, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(VideoAuthorValue)
                            .addComponent(VideoTitleValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VideoQualityText)
                    .addComponent(VideoGenreText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VideoGenreValue)
                    .addComponent(VideoQualityValue, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        VideoInputPanelLayout.setVerticalGroup(
            VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VideoInputlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VideoFileNameText)
                    .addComponent(VideoFileNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VideoAuthorText)
                    .addComponent(VideoAuthorValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VideoQualityText)
                    .addComponent(VideoQualityValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VideoGenreText)
                        .addComponent(VideoGenreValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VideoFileTypeText)
                        .addComponent(VideoFileTypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VideoTitleText)
                        .addComponent(VideoTitleValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VideoInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VideoSizeText)
                    .addComponent(VideoSizeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VideoLengthText)
                    .addComponent(VideoLengthValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        MusicInputlabel.setText("Music Input Area");

        MusicFileNameText.setText("File Name");

        MusicFileTypeText.setText("File Type");

        MusicSizeText.setText("Size (Int)");

        MusicAuthorText.setText("Author");

        MusicTitleText.setText("Title");

        MusicLengthText.setText("Length");

        MusicBItrateText.setText("Bitrate (Int)");

        MusicFeaturedValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicFeaturedValueActionPerformed(evt);
            }
        });

        MusicFeaturedText.setText("Featured");

        MusicGenreValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicGenreValueActionPerformed(evt);
            }
        });

        MusicGenreText.setText("Genre");

        javax.swing.GroupLayout MusicInputPanelLayout = new javax.swing.GroupLayout(MusicInputPanel);
        MusicInputPanel.setLayout(MusicInputPanelLayout);
        MusicInputPanelLayout.setHorizontalGroup(
            MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MusicInputPanelLayout.createSequentialGroup()
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MusicInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MusicInputlabel))
                    .addGroup(MusicInputPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MusicFileNameText)
                            .addComponent(MusicFileTypeText)
                            .addComponent(MusicSizeText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MusicFileNameValue)
                            .addComponent(MusicFileTypeValue)
                            .addComponent(MusicSizeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MusicAuthorText)
                            .addComponent(MusicTitleText)
                            .addComponent(MusicLengthText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MusicLengthValue, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(MusicAuthorValue)
                            .addComponent(MusicTitleValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MusicFeaturedText)
                    .addComponent(MusicGenreText)
                    .addComponent(MusicBItrateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MusicBitrateValue)
                    .addComponent(MusicGenreValue)
                    .addComponent(MusicFeaturedValue, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );
        MusicInputPanelLayout.setVerticalGroup(
            MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MusicInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MusicInputlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusicFileNameText)
                    .addComponent(MusicFileNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusicAuthorText)
                    .addComponent(MusicAuthorValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusicBItrateText)
                    .addComponent(MusicBitrateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MusicFeaturedText)
                        .addComponent(MusicFeaturedValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MusicFileTypeText)
                        .addComponent(MusicFileTypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MusicTitleText)
                        .addComponent(MusicTitleValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MusicGenreText)
                        .addComponent(MusicGenreValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MusicInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MusicSizeText)
                        .addComponent(MusicSizeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MusicLengthText)
                        .addComponent(MusicLengthValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        EbookInputPanel.setPreferredSize(new java.awt.Dimension(678, 147));

        EbookInputlabel.setText("Ebook Input Area");

        EbookFileNameText.setText("File Name");

        EbookFileTypeText.setText("File Type");

        EbookSizeText.setText("Size (Int)");

        EbookAuthorText.setText("Author");

        EbookTitleText.setText("Title");

        EbookPagesText.setText("Pages (Int)");

        EbookGenreText.setText("Genre");

        javax.swing.GroupLayout EbookInputPanelLayout = new javax.swing.GroupLayout(EbookInputPanel);
        EbookInputPanel.setLayout(EbookInputPanelLayout);
        EbookInputPanelLayout.setHorizontalGroup(
            EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EbookInputPanelLayout.createSequentialGroup()
                .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EbookInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EbookInputlabel))
                    .addGroup(EbookInputPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EbookFileNameText)
                            .addComponent(EbookFileTypeText)
                            .addComponent(EbookSizeText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EbookFileNameValue)
                            .addComponent(EbookFileTypeValue)
                            .addComponent(EbookSizeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EbookAuthorText)
                            .addComponent(EbookTitleText)
                            .addComponent(EbookPagesText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EbookPagesValue, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(EbookAuthorValue)
                            .addComponent(EbookTitleValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EbookGenreText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EbookGenreValue, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        EbookInputPanelLayout.setVerticalGroup(
            EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EbookInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EbookInputlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EbookFileNameText)
                    .addComponent(EbookFileNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EbookAuthorText)
                    .addComponent(EbookAuthorValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EbookGenreText)
                    .addComponent(EbookGenreValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EbookFileTypeText)
                    .addComponent(EbookFileTypeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EbookTitleText)
                    .addComponent(EbookTitleValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EbookInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EbookSizeText)
                    .addComponent(EbookSizeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EbookPagesText)
                    .addComponent(EbookPagesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(VideoInputPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(MusicInputPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EbookInputPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EbookInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MusicInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VideoInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EbookInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MusicInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VideoInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertButton.setText("Insert Media");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        MediaTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ebook", "Music", "Video" }));
        MediaTypeCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MediaTypeCBItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nr of objects");

        ObjectCount.setText("0");

        useFile.setText("Use TextFile");
        useFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useFileActionPerformed(evt);
            }
        });

        useDatabase.setText("Use Database");
        useDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDatabaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ObjectCount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(responseField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1041, Short.MAX_VALUE)
                                .addComponent(MediaTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(insertButton))
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(useFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(useDatabase)))
                        .addGap(24, 24, 24))))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ObjectCount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MediaTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertButton)))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(responseField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useFile)
                    .addComponent(useDatabase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ObjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ObjectType", "File Name", "File Type", "Size", "Author", "Title", "Length", "Pages", "Genre", "Artists", "VideoQ", "Bitrate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ObjectTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usingField)
                        .addGap(59, 59, 59))
                    .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usingField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed

        Object selectedItem = MediaTypeCB.getSelectedItem();

        if (selectedItem != null) {
            String selectedItemStr = selectedItem.toString();

            switch (selectedItemStr) {
                case ("Ebook"):

                    String fname = EbookFileNameValue.getText();
                    String ftype = EbookFileTypeValue.getText();
                    String sizestr = EbookSizeValue.getText();
                    String author = EbookAuthorValue.getText();
                    String title = EbookTitleValue.getText();
                    String pagesstr = EbookPagesValue.getText();
                    String genre = EbookGenreValue.getText();

                    try {
                        int size = Integer.valueOf(sizestr);
                        int pages = Integer.valueOf(pagesstr);

                        int objCounter = Integer.valueOf(ObjectCount.getText()); // counts the amount of objects in the table

                        MList.add(new Ebook(fname, ftype, size, author, title, pages, genre)); // object created

                        Object[] row = {"Ebook", MList.get(objCounter).getfileName(), MList.get(objCounter).getitemType(), MList.get(objCounter).getsizeInMb(), MList.get(objCounter).getauthor(), MList.get(objCounter).getTitle(), MList.get(objCounter).getLength(), MList.get(objCounter).getNumberOfPages(), MList.get(objCounter).getGenre(), MList.get(objCounter).getFeaturedArtists(), MList.get(objCounter).getVideoQuality(), MList.get(objCounter).getBitrate()};

                        DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();

                        model.addRow(row);  // add a row of data in table

                        String str = "Ebook;;" + MList.get(objCounter).getfileName() + ";;" + MList.get(objCounter).getitemType() + ";;" + MList.get(objCounter).getsizeInMb() + ";;" + MList.get(objCounter).getauthor() + ";;" + MList.get(objCounter).getTitle() + ";;" + MList.get(objCounter).getLength() + ";;" + MList.get(objCounter).getNumberOfPages() + ";;" + MList.get(objCounter).getGenre() + ";;" + MList.get(objCounter).getFeaturedArtists() + ";;" + MList.get(objCounter).getVideoQuality() + ";;" + MList.get(objCounter).getBitrate();
                        
                        
                        if(usingField.getText().equals("Using TextFile"))
                            writeInFile(str); // look function below
                        else if(usingField.getText().equals("Using Database"))
                            updateDatabase(str);
                        objCounter++;
                        ObjectCount.setText("" + objCounter);
                    } catch (NumberFormatException ex) {
                        responseField.setText("Parsing Error");
                    }

                    break;
                case ("Video"):
                    String fname1 = VideoFileNameValue.getText(); // get the input data
                    String ftype1 = VideoFileTypeValue.getText();
                    String sizestr1 = VideoSizeValue.getText();
                    String author1 = VideoAuthorValue.getText();
                    String title1 = VideoTitleValue.getText();
                    String length = VideoLengthValue.getText();
                    String qualitystr = VideoQualityValue.getText();
                    String genre1 = VideoGenreValue.getText();

                    try {
                        int size1 = Integer.parseInt(sizestr1); // convert some to int
                        int quality = Integer.parseInt(qualitystr);

                        int objCounter = Integer.valueOf(ObjectCount.getText());

                        MList.add(new VideoDvd(fname1, ftype1, size1, author1, title1, length, quality, genre1)); // Create Media Obj

                        Object[] row = {"Video", MList.get(objCounter).getfileName(), MList.get(objCounter).getitemType(), MList.get(objCounter).getsizeInMb(), MList.get(objCounter).getauthor(), MList.get(objCounter).getTitle(), MList.get(objCounter).getLength(), MList.get(objCounter).getNumberOfPages(), MList.get(objCounter).getGenre(), MList.get(objCounter).getFeaturedArtists(), MList.get(objCounter).getVideoQuality(), MList.get(objCounter).getBitrate()};

                        DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();

                        model.addRow(row);

                        String str = "Video;;" + MList.get(objCounter).getfileName() + ";;" + MList.get(objCounter).getitemType() + ";;" + MList.get(objCounter).getsizeInMb() + ";;" + MList.get(objCounter).getauthor() + ";;" + MList.get(objCounter).getTitle() + ";;" + MList.get(objCounter).getLength() + ";;" + MList.get(objCounter).getNumberOfPages() + ";;" + MList.get(objCounter).getGenre() + ";;" + MList.get(objCounter).getFeaturedArtists() + ";;" + MList.get(objCounter).getVideoQuality() + ";;" + MList.get(objCounter).getBitrate();

                        if(usingField.getText().equals("Using TextFile"))
                            writeInFile(str); // look function below
                        else if(usingField.getText().equals("Using Database"))
                            updateDatabase(str);

                        objCounter++;
                        ObjectCount.setText("" + objCounter);
                    } catch (NumberFormatException ex) {
                        responseField.setText("Parsing Error");
                    }
                    break;
                case ("Music"):
                    String fname2 = MusicFileNameValue.getText();
                    String ftype2 = MusicFileTypeValue.getText();
                    String sizestr2 = MusicSizeValue.getText();
                    String author2 = MusicAuthorValue.getText();
                    String title2 = MusicTitleValue.getText();
                    String length2 = MusicLengthValue.getText();
                    String bitratestr = MusicBitrateValue.getText();
                    String featured = MusicFeaturedValue.getText();
                    String genre2 = MusicGenreValue.getText();

                    try {
                        int size2 = Integer.parseInt(sizestr2);
                        int bitrate = Integer.parseInt(bitratestr);

                        int objCounter = Integer.valueOf(ObjectCount.getText());

                        MList.add(new MusicCd(fname2, ftype2, size2, author2, title2, length2, bitrate, featured, genre2));

                        Object[] row = {"Music", MList.get(objCounter).getfileName(), MList.get(objCounter).getitemType(), MList.get(objCounter).getsizeInMb(), MList.get(objCounter).getauthor(), MList.get(objCounter).getTitle(), MList.get(objCounter).getLength(), MList.get(objCounter).getNumberOfPages(), MList.get(objCounter).getGenre(), MList.get(objCounter).getFeaturedArtists(), MList.get(objCounter).getVideoQuality(), MList.get(objCounter).getBitrate()};

                        DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();

                        model.addRow(row);

                        String str = "Music;;" + MList.get(objCounter).getfileName() + ";;" + MList.get(objCounter).getitemType() + ";;" + MList.get(objCounter).getsizeInMb() + ";;" + MList.get(objCounter).getauthor() + ";;" + MList.get(objCounter).getTitle() + ";;" + MList.get(objCounter).getLength() + ";;" + MList.get(objCounter).getNumberOfPages() + ";;" + MList.get(objCounter).getGenre() + ";;" + MList.get(objCounter).getFeaturedArtists() + ";;" + MList.get(objCounter).getVideoQuality() + ";;" + MList.get(objCounter).getBitrate();

                        if(usingField.getText().equals("Using TextFile"))
                            writeInFile(str); // look function below
                        else if(usingField.getText().equals("Using Database"))
                            updateDatabase(str);

                        objCounter++;
                        ObjectCount.setText("" + objCounter);
                    } catch (NumberFormatException ex) {
                        responseField.setText("Parsing Error");
                    }
                    break;
                default:
                    responseField.setText("ComboBox input issue");
                    break;
            }
        }

    }//GEN-LAST:event_insertButtonActionPerformed

    void writeInFile(String str) {

        String[] lineElements = str.split(";;");

        // check if the number of elements is correct (if ;; inputed in gui inputlabel then Split(";;") wont work correctly displaying more elements)
        if (lineElements.length == 12) {
            try {
                FileWriter fw = new FileWriter("Media.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw);

                str = "\n" + str; // println uses newline in end, we want it in start of str

                out.print(str);
                out.close();

                responseField.setText("Object Inserted");

            } catch (IOException e) {
                responseField.setText("Error writing file");
            }
        }

    }

    void updateDatabase(String str){
        
        String[] lineElements = str.split(";;");

        // check if the number of elements is correct (if ;; inputed in gui inputlabel then Split(";;") wont work correctly displaying more elements)
        if (lineElements.length == 12) {
            try {
                Connection conn = DriverManager.getConnection(url);
                Statement stmt = conn.createStatement();
                
                //System.out.println("INSERT INTO Media VALUES ('"+lineElements[0]+"', '"+lineElements[1]+"', '"+lineElements[2]+"', "+lineElements[3]+", '"+lineElements[4]+"', '"+lineElements[5]+"', '"+lineElements[6]+"', "+lineElements[7]+", '"+lineElements[8]+"', '"+lineElements[9]+"', "+lineElements[10]+", "+lineElements[11]+");");
                stmt.executeUpdate("INSERT INTO Media VALUES ('"+lineElements[0]+"', '"+lineElements[1]+"', '"+lineElements[2]+"', "+lineElements[3]+", '"+lineElements[4]+"', '"+lineElements[5]+"', '"+lineElements[6]+"', "+lineElements[7]+", '"+lineElements[8]+"', '"+lineElements[9]+"', "+lineElements[10]+", "+lineElements[11]+");");
                
                conn.close();
                responseField.setText("Object Inserted");

            } catch (SQLException e) {
                responseField.setText("Error updating database");
            }
        }
        
    }

    private void MediaTypeCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MediaTypeCBItemStateChanged
        Object selectedItem = MediaTypeCB.getSelectedItem();

        // get the mediaType selected in comboBox
        // set visible only the selected panel matching the comboBox
        if (selectedItem != null) {
            String selectedItemStr = selectedItem.toString();
            switch (selectedItemStr) {
                case ("Ebook"):
                    EbookInputPanel.setVisible(true);
                    MusicInputPanel.setVisible(false);
                    VideoInputPanel.setVisible(false);
                    break;
                case ("Video"):
                    EbookInputPanel.setVisible(false);
                    MusicInputPanel.setVisible(false);
                    VideoInputPanel.setVisible(true);
                    break;
                case ("Music"):
                    EbookInputPanel.setVisible(false);
                    MusicInputPanel.setVisible(true);
                    VideoInputPanel.setVisible(false);
                    break;
                default:
                    EbookInputPanel.setVisible(false);
                    MusicInputPanel.setVisible(false);
                    VideoInputPanel.setVisible(false);
                    break;
            }
        }
    }//GEN-LAST:event_MediaTypeCBItemStateChanged

    private void MusicFeaturedValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicFeaturedValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicFeaturedValueActionPerformed

    private void MusicGenreValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicGenreValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicGenreValueActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        usingField.setText("No Data Storage Method Used");

        //Cant add media without selecting data storage type
        insertButton.setEnabled(false);

        //bugfix video, music textfield visible if clicked in start
        MusicInputPanel.setVisible(false);
        VideoInputPanel.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void useFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useFileActionPerformed
        //when switching from text to db fix object count
        ObjectCount.setText("0");
        int objCount = 0;

        //now u can insert media
        insertButton.setEnabled(true);

        //Clear table and objectList
        clearTable();
        MList.clear();

        try {
            File file = new File("Media.txt");

            if (file.createNewFile()) {
                responseField.setText("File Created");
            } else {
                responseField.setText("File Found");

                try {
                    String line;    //Holds rows of text

                    BufferedReader br = new BufferedReader(new FileReader(file));

                    // Example of a row of data => Ebook;;Ebook1;;PDF;;34;;Samo;;LearningJava;;-1;;56;;Learning;;-1;;-1;;-1
                    // First data tells the Object Type. Could be useful later
                    while ((line = br.readLine()) != null) {      //For each line of the text file
                        String lineArr[] = line.split(";;");    // cut the line in data array

                        if (lineArr.length == 12) {               //Check data array amount . if different from 12 dont insert the data in table

                            Object[] row = lineArr;

                            if (lineArr[0].equals("Ebook")) {
                                MList.add(new Ebook(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], Integer.valueOf(lineArr[7]), lineArr[8]));
                            } else if (lineArr[0].equals("Music")) {
                                MList.add(new MusicCd(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], lineArr[6], Integer.valueOf(lineArr[11]), lineArr[9], lineArr[8]));
                            } else if (lineArr[0].equals("Video")) {
                                MList.add(new VideoDvd(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], lineArr[6], Integer.valueOf(lineArr[10]), lineArr[8]));
                            } else {
                                continue;
                            }

                            objCount++;                   // increment for the object count text label

                            DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();

                            model.addRow(row);
                        }
                    }

                    ObjectCount.setText("" + objCount); // update the textlabel to the amount of objects
                    usingField.setText("Using TextFile");   // update using textlabel
                    useFile.setEnabled(false);          // Disable button
                    useDatabase.setEnabled(true);
                    
                } catch (Exception err) {
                    System.out.println("[-] Unable to open file");
                }

            }

        } catch (IOException err) {
            System.out.println("[-] File error");
        }
    }//GEN-LAST:event_useFileActionPerformed

    private void useDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDatabaseActionPerformed

        //now u can insert media
        insertButton.setEnabled(true);

        SelectDatabase dbSelectFrame = new SelectDatabase();
        dbSelectFrame.setVisible(true);

        dbSelectFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dbSelectFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {

                int objCount = 0;

                if (dbSelectFrame.connected) {
                    
                    responseField.setText("Connected to DB");
                    //when switching from text to db fix object count
                    ObjectCount.setText("0");
                    //Clear table and objectList
                    clearTable();
                    MList.clear();

                    url = dbSelectFrame.successUrl;

                    try {
                        Connection conn = DriverManager.getConnection(url);

                        Statement stmt = null;
                        String query = "select * from Media";
                        try {
                            stmt = conn.createStatement();

                            ResultSet rs = stmt.executeQuery(query);

                            ArrayList<String> row = new ArrayList<String>();

                            while (rs.next()) {
                                row.add(rs.getString("ObjectType"));
                                row.add(rs.getString("FileName"));
                                row.add(rs.getString("FileType"));
                                row.add(String.valueOf(rs.getInt("Size")));
                                row.add(rs.getString("Author"));
                                row.add(rs.getString("Title"));
                                row.add(rs.getString("Length"));
                                row.add(String.valueOf(rs.getInt("Pages")));
                                row.add(rs.getString("Genre"));
                                row.add(rs.getString("Artist"));
                                row.add(String.valueOf(rs.getInt("VideoQ")));
                                row.add(String.valueOf(rs.getInt("Bitrate")));

                                String[] lineArr = new String[row.size()];
                                lineArr = row.toArray(lineArr);

                                if (lineArr.length == 12) {               //Check data array amount . if different from 12 dont insert the data in table

                                    Object[] row1 = lineArr;

                                    if (lineArr[0].equals("Ebook")) {
                                        MList.add(new Ebook(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], Integer.valueOf(lineArr[7]), lineArr[8]));
                                    } else if (lineArr[0].equals("Music")) {
                                        MList.add(new MusicCd(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], lineArr[6], Integer.valueOf(lineArr[11]), lineArr[9], lineArr[8]));
                                    } else if (lineArr[0].equals("Video")) {
                                        MList.add(new VideoDvd(lineArr[1], lineArr[2], Integer.valueOf(lineArr[3]), lineArr[4], lineArr[5], lineArr[6], Integer.valueOf(lineArr[10]), lineArr[8]));
                                    } else {
                                        continue;
                                    }

                                    objCount++;                   // increment for the object count text label

                                    DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();

                                    model.addRow(row1);

                                    row.clear();

                                }

                            }

                            ObjectCount.setText("" + objCount); // update the textlabel to the amount of objects
                            usingField.setText("Using Database");   // update using textlabel
                            useFile.setEnabled(true);          // Disable button
                            useDatabase.setEnabled(false);
                            conn.close();
                        } catch (SQLException e) {
                            throw new Error("Problem", e);
                        } finally {
                            if (stmt != null) {
                                try {
                                    stmt.close();
                                } catch (SQLException ex) {
                                    System.out.println("Error!");
                                }
                            }
                        }

                    } catch (SQLException ex) {
                        responseField.setText("Couldnt connect to Database");
                    }

                }

            }
        });


    }//GEN-LAST:event_useDatabaseActionPerformed

    void clearTable() {
        DefaultTableModel model = (DefaultTableModel) ObjectTable.getModel();
        model.setRowCount(0);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EbookAuthorText;
    private javax.swing.JTextField EbookAuthorValue;
    private javax.swing.JLabel EbookFileNameText;
    private javax.swing.JTextField EbookFileNameValue;
    private javax.swing.JLabel EbookFileTypeText;
    private javax.swing.JTextField EbookFileTypeValue;
    private javax.swing.JLabel EbookGenreText;
    private javax.swing.JTextField EbookGenreValue;
    private javax.swing.JPanel EbookInputPanel;
    private javax.swing.JLabel EbookInputlabel;
    private javax.swing.JLabel EbookPagesText;
    private javax.swing.JTextField EbookPagesValue;
    private javax.swing.JLabel EbookSizeText;
    private javax.swing.JTextField EbookSizeValue;
    private javax.swing.JLabel EbookTitleText;
    private javax.swing.JTextField EbookTitleValue;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JComboBox<String> MediaTypeCB;
    private javax.swing.JLabel MusicAuthorText;
    private javax.swing.JTextField MusicAuthorValue;
    private javax.swing.JLabel MusicBItrateText;
    private javax.swing.JTextField MusicBitrateValue;
    private javax.swing.JLabel MusicFeaturedText;
    private javax.swing.JTextField MusicFeaturedValue;
    private javax.swing.JLabel MusicFileNameText;
    private javax.swing.JTextField MusicFileNameValue;
    private javax.swing.JLabel MusicFileTypeText;
    private javax.swing.JTextField MusicFileTypeValue;
    private javax.swing.JLabel MusicGenreText;
    private javax.swing.JTextField MusicGenreValue;
    private javax.swing.JPanel MusicInputPanel;
    private javax.swing.JLabel MusicInputlabel;
    private javax.swing.JLabel MusicLengthText;
    private javax.swing.JTextField MusicLengthValue;
    private javax.swing.JLabel MusicSizeText;
    private javax.swing.JTextField MusicSizeValue;
    private javax.swing.JLabel MusicTitleText;
    private javax.swing.JTextField MusicTitleValue;
    private javax.swing.JLabel ObjectCount;
    private javax.swing.JTable ObjectTable;
    private javax.swing.JLabel VideoAuthorText;
    private javax.swing.JTextField VideoAuthorValue;
    private javax.swing.JLabel VideoFileNameText;
    private javax.swing.JTextField VideoFileNameValue;
    private javax.swing.JLabel VideoFileTypeText;
    private javax.swing.JTextField VideoFileTypeValue;
    private javax.swing.JLabel VideoGenreText;
    private javax.swing.JTextField VideoGenreValue;
    private javax.swing.JPanel VideoInputPanel;
    private javax.swing.JLabel VideoInputlabel;
    private javax.swing.JLabel VideoLengthText;
    private javax.swing.JTextField VideoLengthValue;
    private javax.swing.JLabel VideoQualityText;
    private javax.swing.JTextField VideoQualityValue;
    private javax.swing.JLabel VideoSizeText;
    private javax.swing.JTextField VideoSizeValue;
    private javax.swing.JLabel VideoTitleText;
    private javax.swing.JTextField VideoTitleValue;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel responseField;
    private javax.swing.JButton useDatabase;
    private javax.swing.JButton useFile;
    private javax.swing.JLabel usingField;
    // End of variables declaration//GEN-END:variables
}
